### ISSUE TITLE
Upgrade Moodle 4.3 -> Moodle 4.4 gives error

### ISSUE THREAD

**Issue by Richardvi** [danmarsden/moodle-block_attendance#21] opened 2024-07-17 13:08 UTC
When upgrading Moodle 4.3 to Moodle 4.4 you will get to the screen to check for plugin updates. Usually I use this screen to immediately get all the updates of cursom plugins into my new Moodle version. However, Attendance breaks this for all updates available with this error message:

![image](https://github.com/user-attachments/assets/879b3e89-fcfd-4b5c-aac9-2bdc95efefa6)

Somehow the wrong Moodle version is being detected. This is a real pain, because this failure leads to installing ALL plugins manually. (in my case around 50)

**Comment by Richardvi** [comment] 2024-07-17 13:09
I was installing the daily latest version of Moodle....

**Comment by danmarsden** [comment] 2024-07-17 22:53
Hi @Richardvi I don't think there's much I can do about this on my end - I note you've also reported this against the "block" rather than the "module" and the messages above refer to the "module"

the error is saying that your moodle codebase is older than 2024041200 which is the version of the Moodle 4.4.0 release so something in your site is reporting that it is an older version (4.3)  instead of 4.4 but I think you'd need to do some further investigation on your end to discover what caused that - I'm closing this off for now because I don't think there's anything I can do to help or reproduce this further sorry! - I don't think this is a bug with the attendance module, but more likely to be something either in Moodle core or related to the way you upgraded to 4.4 or maybe some form of invalid caching on your server.

**Closed by danmarsden** 2024-07-17 22:53 UTC

**Comment by Richardvi** [comment] 2024-07-18 09:54
Hi Dan,

I don't think it's a bug at our side, let me explain why.

We did an upgrade from Moodle 4.3 to Moodle 4.4. We have around 50 custom modules installed. When updating Moodle, you get tot the screen where you can also check for updates for custom modules.

What I think happened is this: all the custom modules detected the version of Moodle that I was upgrading to (4.4) except for the attendance module. The attendance module detected the Moodle version I was upgrading from (4.3).

So my guess is that upon installing the attendance module the check for the Moodle version it is being installed upon is not the same as from the other custom modules.

Could you verify that? 

And my apologies for posting it in the wrong Github (the block in stead of the module).

**Comment by danmarsden** [comment] 2024-07-19 00:39
Hey Richard - sorry this isn't something I have time to do "for free" - at the moment I can't see anything that would cause this on my side - the versions in both the block and module look correct to me - installing the plugin on an existing site and upgraded site is working fine on my side, but I don't use the same process as you have.

If you do find the cause and it points to a specific issue within the attendance let me know,  I'll also keep an eye out for future reports of other people that have the same issue that might point towards this being an issue specifically with attendance and not something specific to your Moodle instance.

**Comment by danmarsden** [comment] 2024-07-21 23:09
no worries - I appreciate the time you took to create the request - but my current assessment of this reported issue suggests it's not a bug with the attendance code - I can't see anything on the attendance side that would cause the issue - If you are able to find out more information that points to an issue with attendance let me know - but I suspect as you have already worked around the issue, unless someone else runs into a similar issue there's nothing else we can do here at this stage.
